#!/usr/bin/env python3
"""Rename FM2 Ghost duelist portraits from D<ID>.jpg to <slug>.webp.

The portrait files are already encoded as WebP, despite their ``.jpg``
extensions. Duelist IDs and output slugs are read from the Ghost data file so
the filenames always match the URLs generated by the app.

Run without ``--apply`` to preview the operation first.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Final


SOURCE_NAME_PATTERN: Final = re.compile(r"^D0*(\d+)\.jpg$", re.IGNORECASE)
SLUG_PATTERN: Final = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
WEBP_HEADER_LENGTH: Final = 12


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Rename FM2 Ghost portraits from D<ID>.jpg to <slug>.webp"
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Perform the renames. Without this flag, only a dry run is shown.",
    )
    return parser.parse_args()


def read_duelists(path: Path) -> list[dict[str, Any]]:
    records: Any = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(records, list) or not records:
        raise ValueError(f"{path} must contain a non-empty array")

    ids: set[int] = set()
    slugs: set[str] = set()
    for index, record in enumerate(records):
        if not isinstance(record, dict):
            raise ValueError(f"Duelist at index {index} must be an object")
        duelist_id = record.get("id")
        slug = record.get("slug")
        if not isinstance(duelist_id, int) or isinstance(duelist_id, bool) or duelist_id < 1:
            raise ValueError(f"Duelist at index {index} has an invalid ID: {duelist_id!r}")
        if not isinstance(slug, str) or not SLUG_PATTERN.fullmatch(slug):
            raise ValueError(f"Duelist #{duelist_id} has an invalid slug: {slug!r}")
        if duelist_id in ids:
            raise ValueError(f"Duplicate duelist ID: {duelist_id}")
        if slug in slugs:
            raise ValueError(f"Duplicate duelist slug: {slug}")
        ids.add(duelist_id)
        slugs.add(slug)

    expected_ids = set(range(1, len(records) + 1))
    if ids != expected_ids:
        missing = sorted(expected_ids - ids)
        unexpected = sorted(ids - expected_ids)
        raise ValueError(
            f"Duelist IDs must be contiguous from 1 to {len(records)}; "
            f"missing={missing}, unexpected={unexpected}"
        )
    return records


def is_webp(path: Path) -> bool:
    with path.open("rb") as image_file:
        header = image_file.read(WEBP_HEADER_LENGTH)
    return len(header) == WEBP_HEADER_LENGTH and header[:4] == b"RIFF" and header[8:] == b"WEBP"


def discover_sources(directory: Path) -> tuple[dict[int, Path], list[Path]]:
    candidates: dict[int, list[Path]] = {}
    invalid_names: list[Path] = []

    for path in sorted(directory.iterdir()):
        if not path.is_file() or path.suffix.lower() != ".jpg":
            continue
        match = SOURCE_NAME_PATTERN.fullmatch(path.name)
        if not match:
            invalid_names.append(path)
            continue
        candidates.setdefault(int(match.group(1)), []).append(path)

    duplicates = {duelist_id: paths for duelist_id, paths in candidates.items() if len(paths) > 1}
    if duplicates:
        details = "; ".join(
            f"#{duelist_id}: {', '.join(path.name for path in paths)}"
            for duelist_id, paths in sorted(duplicates.items())
        )
        raise ValueError(f"Multiple source files matched the same duelist ID: {details}")

    return {duelist_id: paths[0] for duelist_id, paths in candidates.items()}, invalid_names


def validate_and_plan(
    directory: Path,
    duelists: list[dict[str, Any]],
) -> tuple[list[tuple[Path, Path]], int]:
    sources, invalid_source_names = discover_sources(directory)
    expected_by_id = {duelist["id"]: duelist for duelist in duelists}
    expected_by_slug = {duelist["slug"]: duelist for duelist in duelists}

    unexpected_source_ids = sorted(set(sources) - set(expected_by_id))
    if invalid_source_names or unexpected_source_ids:
        details = [path.name for path in invalid_source_names]
        details.extend(f"D{duelist_id}.jpg" for duelist_id in unexpected_source_ids)
        raise ValueError("Unrecognized portrait source files: " + ", ".join(details))

    webp_files = [
        path
        for path in sorted(directory.iterdir())
        if path.is_file() and path.suffix.lower() == ".webp"
    ]
    destinations: dict[str, Path] = {}
    invalid_destination_names: list[str] = []
    for path in webp_files:
        expected = expected_by_slug.get(path.stem)
        if expected is None or path.name != f"{expected['slug']}.webp":
            invalid_destination_names.append(path.name)
            continue
        destinations[path.stem] = path
    if invalid_destination_names:
        raise ValueError(
            "Unrecognized normalized portrait files: "
            + ", ".join(invalid_destination_names)
        )

    plan: list[tuple[Path, Path]] = []
    missing: list[str] = []
    collisions: list[str] = []
    files_to_validate: list[Path] = []
    for duelist in duelists:
        duelist_id = duelist["id"]
        slug = duelist["slug"]
        source = sources.get(duelist_id)
        destination = destinations.get(slug)
        if source and destination:
            collisions.append(f"#{duelist_id} {slug}")
        elif source:
            plan.append((source, directory / f"{slug}.webp"))
            files_to_validate.append(source)
        elif destination:
            files_to_validate.append(destination)
        else:
            missing.append(f"#{duelist_id} {slug}")

    if collisions:
        raise ValueError("Both source and destination exist for: " + ", ".join(collisions))
    if missing:
        raise ValueError("Missing portraits for: " + ", ".join(missing))

    invalid_webp_content = [path.name for path in files_to_validate if not is_webp(path)]
    if invalid_webp_content:
        raise ValueError(
            "These portraits are not WebP images and require conversion: "
            + ", ".join(invalid_webp_content)
        )

    return plan, len(destinations)


def apply_renames(plan: list[tuple[Path, Path]]) -> None:
    completed: list[tuple[Path, Path]] = []
    try:
        for source, destination in plan:
            source.rename(destination)
            completed.append((source, destination))
    except OSError as error:
        rollback_errors: list[str] = []
        for source, destination in reversed(completed):
            try:
                destination.rename(source)
            except OSError as rollback_error:
                rollback_errors.append(f"{destination.name}: {rollback_error}")
        message = f"Rename failed after {len(completed)} files: {error}"
        if rollback_errors:
            message += "; rollback also failed for " + ", ".join(rollback_errors)
        raise RuntimeError(message) from error


def main() -> int:
    arguments = parse_arguments()
    project_root = Path(__file__).resolve().parents[2]
    data_path = project_root / "src" / "data" / "fm2-ghost" / "duelists.json"
    image_directory = project_root / "public" / "mods" / "fm2-ghost" / "duelists"

    if not image_directory.is_dir():
        print(f"Duelist image directory does not exist: {image_directory}", file=sys.stderr)
        return 1

    try:
        duelists = read_duelists(data_path)
        plan, already_normalized = validate_and_plan(image_directory, duelists)
        print(f"Validated WebP portraits: {len(duelists)}")
        print(f"Already normalized: {already_normalized}")
        print(f"Renames required: {len(plan)}")

        if not plan:
            print("No changes needed.")
            return 0

        if not arguments.apply:
            print(f"First: {plan[0][0].name} -> {plan[0][1].name}")
            print(f"Last:  {plan[-1][0].name} -> {plan[-1][1].name}")
            print("Dry run only. Re-run with --apply to rename the files.")
            return 0

        apply_renames(plan)

        remaining_plan, normalized_count = validate_and_plan(image_directory, duelists)
        if remaining_plan or normalized_count != len(duelists):
            raise RuntimeError("Post-rename validation did not find the complete normalized set")

        print(f"Renamed: {len(plan)}")
        print(f"Normalized portraits present: {normalized_count}")
        return 0
    except (OSError, RuntimeError, ValueError, json.JSONDecodeError) as error:
        print(f"Ghost duelist image normalization failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
